import { ArrowRight, CalendarDays, CheckCircle2, Clock3, Loader2, Search, Sparkles, UsersRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useCreateVisit, useGetDashboardSummary, useListProviders, getGetDashboardSummaryQueryKey, getListProvidersQueryKey, getListVisitsQueryKey } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { ProviderAvatar } from '@/components/provider-avatar';
import { formatTime } from '@/lib/format';
import { useToast } from '@/hooks/use-toast';

export default function Dashboard() {
  const queryClient = useQueryClient(); const { toast } = useToast();
  const [search, setSearch] = useState(''); const [selected, setSelected] = useState<number | null>(null); const [service, setService] = useState('');
  const summary = useGetDashboardSummary(); const providers = useListProviders({ limit: 20, search: search.trim() || undefined }); const createVisit = useCreateVisit();
  const list = providers.data ?? []; const filtered = useMemo(() => list.filter((p) => `${p.name} ${p.company} ${p.defaultService} ${p.rg}`.toLowerCase().includes(search.toLowerCase())), [list, search]);
  const visits = summary.data?.recentVisits ?? [];
  function registerVisit() {
    if (!selected) {
      toast({ title: 'Selecione um prestador', description: 'Digite um nome ou empresa e escolha um resultado da lista.' });
      return;
    }
    if (service.trim().length < 2) {
      toast({ title: 'Informe o serviço', description: 'Descreva o serviço realizado hoje antes de registrar a entrada.' });
      return;
    }
    createVisit.mutate({ data: { providerId: selected, service: service.trim() } }, { onSuccess: () => { toast({ title: 'Entrada registrada', description: 'O horário foi salvo no momento em que a entrada foi confirmada.' }); setSelected(null); setSearch(''); setService(''); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); queryClient.invalidateQueries({ queryKey: getListProvidersQueryKey() }); queryClient.invalidateQueries({ queryKey: getListVisitsQueryKey() }); }, onError: () => { toast({ title: 'Não foi possível registrar', description: 'Confira a conexão com o servidor e tente novamente.', variant: 'destructive' }); } });
  }
  return <div className="space-y-8">
    <section className="rise-in flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
      <div><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.2em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" />{new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</div><h1 className="text-3xl font-bold tracking-[-.04em] text-foreground sm:text-[40px]">Bom dia, Marina<span className="text-accent">.</span></h1><p className="mt-2 max-w-lg text-sm text-muted-foreground">A recepção está tranquila. Reconheça um retorno ou registre uma nova chegada.</p></div>
      <Link href="/cadastro" data-testid="link-new-provider-dashboard" className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-4 py-3 text-sm font-semibold text-foreground transition-all hover:-translate-y-0.5 hover:border-primary/40"><UsersRound className="h-4 w-4 text-primary" />Primeiro cadastro <ArrowRight className="ml-2 h-4 w-4 text-muted-foreground" /></Link>
    </section>
    <section className="grid gap-3 sm:grid-cols-3">
      {[{ label: 'Visitas hoje', value: summary.data?.visitsToday, icon: Clock3, note: 'entradas registradas' }, { label: 'Prestadores ativos', value: summary.data?.totalProviders, icon: UsersRound, note: 'identidades no sistema' }, { label: 'Esperados agora', value: summary.data?.currentlyExpected, icon: CalendarDays, note: 'com chegada prevista' }].map(({ label, value, icon: Icon, note }, index) => <div key={label} className={`rise-in delay-${index + 1} rounded-2xl border border-border bg-card p-5`} data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 font-mono text-3xl font-bold tracking-[-.06em]">{summary.isLoading ? <span className="skeleton inline-block h-8 w-14 rounded-md" /> : value ?? 0}</p></div><div className="grid h-9 w-9 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div></div><p className="mt-4 text-[11px] text-muted-foreground">{note}</p></div>)}
    </section>
    <section className="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(330px,.8fr)]">
      <div className="rounded-2xl border border-border bg-card p-5 sm:p-6">
        <div className="mb-5 flex items-start justify-between"><div><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-accent-foreground" /><h2 className="text-lg font-bold tracking-tight">Chegada rápida</h2></div><p className="mt-1 text-xs text-muted-foreground">Para quem já tem registro — só precisamos do serviço de hoje.</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider text-primary">Retorno</span></div>
         <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input value={search} onChange={(e) => { setSearch(e.target.value); setSelected(null); }} data-testid="input-provider-search" placeholder="Buscar por nome, empresa ou RG..." className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-4 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/10" /></div>
          {search && <div className="mt-2 max-h-52 overflow-y-auto rounded-xl border border-border bg-background p-1.5 shadow-lg">{providers.isFetching ? <div className="px-3 py-5 text-center text-xs text-muted-foreground">Buscando prestadores...</div> : filtered.length ? filtered.map((provider) => <button type="button" key={provider.id} onClick={() => { setSelected(provider.id); setSearch(provider.name); setService(provider.defaultService); }} data-testid={`button-select-provider-${provider.id}`} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors hover:bg-secondary ${selected === provider.id ? 'bg-secondary' : ''}`}><ProviderAvatar name={provider.name} photo={provider.photoData} size="sm" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{provider.name}</span><span className="block truncate text-[11px] text-muted-foreground">{provider.company}</span></span>{selected === provider.id && <CheckCircle2 className="h-4 w-4 text-primary" />}</button>) : <div className="px-3 py-5 text-center text-xs text-muted-foreground">Nenhum prestador encontrado.</div>}</div>}
        {selected ? <div className="mt-4 flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/5 p-3"><ProviderAvatar name={list.find((p) => p.id === selected)?.name ?? ''} photo={list.find((p) => p.id === selected)?.photoData} size="sm" /><div className="min-w-0 flex-1"><p className="text-xs font-semibold">Prestador selecionado</p><p className="truncate text-sm">{list.find((p) => p.id === selected)?.name}</p></div><button type="button" onClick={() => { setSelected(null); setSearch(''); }} data-testid="button-clear-provider" className="text-xs text-muted-foreground hover:text-foreground">Trocar</button></div> : <div className="mt-4 flex items-center gap-2 rounded-xl bg-muted/50 p-3 text-xs text-muted-foreground"><Search className="h-4 w-4 shrink-0" />Digite para localizar uma identidade já cadastrada.</div>}
           <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={service} onChange={(e) => setService(e.target.value)} data-testid="input-quick-service" placeholder="Serviço realizado hoje" disabled={!selected} className="h-11 rounded-xl border border-input bg-background px-3 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary disabled:cursor-not-allowed disabled:opacity-55" /><button type="button" disabled={createVisit.isPending} onClick={registerVisit} data-testid="button-register-visit" className="flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:pointer-events-none disabled:opacity-50">{createVisit.isPending && <Loader2 className="h-4 w-4 animate-spin" />}Registrar entrada</button></div>
      </div>
      <div className="rounded-2xl bg-sidebar p-5 text-sidebar-foreground sm:p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-bold tracking-tight">Chegadas recentes</h2><p className="mt-1 text-xs text-sidebar-foreground/55">Movimento de hoje</p></div><Link href="/historico" data-testid="link-see-history" className="text-xs font-semibold text-sidebar-primary hover:underline">Ver todas</Link></div>{summary.isLoading ? <div className="space-y-4">{[1, 2, 3].map((i) => <div key={i} className="flex gap-3"><div className="skeleton h-9 w-9 rounded-lg opacity-20" /><div className="flex-1"><div className="skeleton h-3 w-3/4 rounded opacity-20" /><div className="skeleton mt-2 h-2 w-1/2 rounded opacity-20" /></div></div>)}</div> : visits.length ? <div className="space-y-4">{visits.slice(0, 5).map((visit) => <div key={visit.id} className="flex items-center gap-3" data-testid={`recent-visit-${visit.id}`}><ProviderAvatar name={visit.providerName} photo={visit.photoData} size="sm" /><div className="min-w-0 flex-1"><Link href={`/prestadores/${visit.providerId}`} data-testid={`link-recent-provider-${visit.providerId}`} className="block truncate text-sm font-semibold hover:text-sidebar-primary hover:underline">{visit.providerName}</Link><p className="truncate text-[11px] text-sidebar-foreground/50">{visit.company} · {visit.service}</p></div><span className="font-mono text-[10px] text-sidebar-foreground/50">{formatTime(visit.enteredAt)}</span></div>)}</div> : <div className="rounded-xl border border-dashed border-sidebar-foreground/20 p-5 text-center text-xs text-sidebar-foreground/55">As próximas entradas aparecerão aqui.</div>}</div>
    </section>
  </div>;
}