import { CalendarDays, ChevronRight, Clock3, Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useListVisits } from '@workspace/api-client-react';
import { ProviderAvatar } from '@/components/provider-avatar';
import { formatDate, formatTime } from '@/lib/format';

export default function Historico() {
  const visitsQuery = useListVisits({ limit: 100 }); const [search, setSearch] = useState('');
  const visits = useMemo(() => (visitsQuery.data ?? []).filter((v) => `${v.providerName} ${v.company} ${v.service}`.toLowerCase().includes(search.toLowerCase())), [visitsQuery.data, search]);
  return <div className="space-y-7"><section className="rise-in flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-primary"><Clock3 className="h-3.5 w-3.5" />Linha do tempo</div><h1 className="text-3xl font-bold tracking-[-.04em]">Histórico de visitas</h1><p className="mt-2 text-sm text-muted-foreground">Cada entrada registrada na recepção, em um só lugar.</p></div><button type="button" data-testid="button-history-filter" className="flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-4 py-2.5 text-xs font-semibold text-muted-foreground hover:text-foreground"><SlidersHorizontal className="h-4 w-4" />Filtros</button></section>
    <section className="rise-in delay-1 rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="relative"><Search className="absolute left-3.5 top-3 h-4 w-4 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} data-testid="input-history-search" placeholder="Buscar por prestador, empresa ou serviço..." className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-4 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10" /></div></section>
    <section className="rise-in delay-2 overflow-hidden rounded-2xl border border-border bg-card">{visitsQuery.isLoading ? <div className="space-y-4 p-6">{[1,2,3,4].map((i) => <div className="flex items-center gap-4" key={i}><div className="skeleton h-10 w-10 rounded-xl" /><div className="flex-1"><div className="skeleton h-3 w-1/3 rounded" /><div className="skeleton mt-2 h-2 w-1/2 rounded" /></div></div>)}</div> : visitsQuery.isError ? <div className="p-12 text-center"><p className="font-semibold">Não foi possível carregar o histórico.</p><p className="mt-1 text-sm text-muted-foreground">Tente atualizar a página.</p></div> : visits.length ? <div className="divide-y divide-border">{visits.map((visit) => <div key={visit.id} data-testid={`row-visit-${visit.id}`} className="flex flex-col gap-3 px-5 py-4 transition-colors hover:bg-secondary/35 sm:flex-row sm:items-center sm:gap-5"><ProviderAvatar name={visit.providerName} photo={visit.photoData} size="md" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{visit.providerName}</p><p className="mt-1 truncate text-xs text-muted-foreground">{visit.company}</p></div><div className="flex items-center gap-2 sm:w-52"><span className="rounded-lg bg-secondary px-2.5 py-1.5 text-xs font-medium text-secondary-foreground">{visit.service}</span></div><div className="flex items-center gap-2 text-xs text-muted-foreground sm:w-44 sm:justify-end"><CalendarDays className="h-3.5 w-3.5" /><span>{formatDate(visit.enteredAt)} · {formatTime(visit.enteredAt)}</span><ChevronRight className="ml-1 hidden h-4 w-4 text-border sm:block" /></div></div>)}</div> : <div className="p-14 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-secondary text-muted-foreground"><Clock3 className="h-5 w-5" /></div><h3 className="font-bold">{search ? 'Nenhum resultado' : 'Ainda não há visitas'}</h3><p className="mx-auto mt-1 max-w-xs text-sm text-muted-foreground">{search ? 'Tente outro nome, empresa ou serviço.' : 'As entradas registradas começarão a aparecer nesta linha do tempo.'}</p>{!search && <Link href="/" data-testid="link-history-dashboard" className="mt-5 inline-flex text-xs font-semibold text-primary hover:underline">Registrar uma entrada</Link>}</div>}</section>
  </div>;
}