import { ArrowUpRight, Building2, Search, UserRound, UsersRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useListProviders } from '@workspace/api-client-react';
import { ProviderAvatar } from '@/components/provider-avatar';
import { formatDate } from '@/lib/format';

export default function Prestadores() {
  const [search, setSearch] = useState(''); const query = useListProviders({ limit: 100 }); const providers = useMemo(() => (query.data ?? []).filter((p) => `${p.name} ${p.company} ${p.defaultService}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  return <div className="space-y-7"><section className="rise-in flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-primary"><UsersRound className="h-3.5 w-3.5" />Diretório</div><h1 className="text-3xl font-bold tracking-[-.04em]">Prestadores</h1><p className="mt-2 text-sm text-muted-foreground">Identidades conhecidas pela unidade e prontas para o próximo retorno.</p></div><Link href="/cadastro" data-testid="link-directory-cadastro" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5"><UserRound className="h-4 w-4" />Cadastrar prestador</Link></section>
    <section className="rise-in delay-1 rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="relative"><Search className="absolute left-3.5 top-3 h-4 w-4 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} data-testid="input-directory-search" placeholder="Buscar nome, empresa ou serviço..." className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-4 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10" /></div></section>
    {query.isLoading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map((i) => <div key={i} className="h-40 animate-pulse rounded-2xl border border-border bg-card p-5"><div className="skeleton h-11 w-11 rounded-xl" /><div className="skeleton mt-4 h-3 w-2/3 rounded" /><div className="skeleton mt-2 h-2 w-1/2 rounded" /></div>)}</div> : query.isError ? <div className="rounded-2xl border border-border bg-card p-12 text-center"><p className="font-semibold">Diretório indisponível</p><p className="mt-1 text-sm text-muted-foreground">Não conseguimos carregar os prestadores agora.</p></div> : providers.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{providers.map((provider) => <Link href={`/prestadores/${provider.id}`} key={provider.id} data-testid={`card-provider-${provider.id}`} className="group rounded-2xl border border-border bg-card p-5 transition-all hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-[0_10px_30px_hsl(174_43%_32%/.08)]"><div className="flex items-start justify-between"><ProviderAvatar name={provider.name} photo={provider.photoData} size="md" /><ArrowUpRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-primary" /></div><h3 className="mt-4 font-bold tracking-tight">{provider.name}</h3><div className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Building2 className="h-3.5 w-3.5" />{provider.company}</div><div className="mt-5 flex items-end justify-between border-t border-border pt-4"><div><p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Serviço padrão</p><p className="mt-1 max-w-[170px] truncate text-xs font-medium">{provider.defaultService}</p></div><div className="text-right"><p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Visitas</p><p className="mt-1 font-mono text-sm font-bold text-primary">{provider.visitCount}</p></div></div></Link>)}</div> : <div className="rounded-2xl border border-dashed border-border bg-card p-14 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-secondary text-muted-foreground"><UsersRound className="h-5 w-5" /></div><h3 className="font-bold">{search ? 'Nenhum prestador encontrado' : 'Diretório vazio'}</h3><p className="mx-auto mt-1 max-w-xs text-sm text-muted-foreground">{search ? 'Tente uma busca diferente.' : 'Cadastre o primeiro prestador para começar.'}</p>{!search && <Link href="/cadastro" data-testid="link-empty-cadastro" className="mt-5 inline-flex text-xs font-semibold text-primary hover:underline">Cadastrar agora</Link>}</div>}
  </div>;
}