import { ArrowLeft, Building2, CalendarDays, Edit3, FileText, Save, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'wouter';
import { getGetProviderQueryKey, useGetProvider, useUpdateProvider } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { ProviderAvatar } from '@/components/provider-avatar';
import { formatDate } from '@/lib/format';
import { useToast } from '@/hooks/use-toast';

export default function PrestadorDetalhe() {
  const params = useParams<{ id: string }>(); const id = Number(params.id); const query = useGetProvider(id, { query: { queryKey: getGetProviderQueryKey(id) } }); const update = useUpdateProvider(); const queryClient = useQueryClient(); const { toast } = useToast(); const [editing, setEditing] = useState(false); const [form, setForm] = useState({ name: '', rg: '', company: '', defaultService: '' });
  useEffect(() => { if (query.data) setForm({ name: query.data.name, rg: query.data.rg, company: query.data.company, defaultService: query.data.defaultService }); }, [query.data]);
  if (query.isLoading) return <div className="mx-auto max-w-3xl space-y-4"><div className="skeleton h-8 w-32 rounded" /><div className="skeleton h-64 rounded-2xl" /></div>;
  if (query.isError || !query.data) return <div className="p-12 text-center"><p className="font-bold">Registro não encontrado</p><Link href="/prestadores" data-testid="link-back-directory-error" className="mt-3 inline-flex text-sm text-primary hover:underline">Voltar ao diretório</Link></div>;
  const provider = query.data;
  function save() { update.mutate({ id, data: form }, { onSuccess: (updated) => { queryClient.setQueryData(getGetProviderQueryKey(id), updated); setEditing(false); toast({ title: 'Registro atualizado' }); } }); }
  return <div className="mx-auto max-w-4xl space-y-6"><div className="flex items-center gap-4"><Link href="/prestadores" data-testid="link-back-directory" className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-card text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /></Link><div><div className="mb-1 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-primary"><UserRound className="h-3 w-3" />Ficha do prestador</div><h1 className="text-2xl font-bold tracking-tight">Registro individual</h1></div></div>
    <section className="rise-in rounded-2xl border border-border bg-card p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><ProviderAvatar name={provider.name} photo={provider.photoData} size="lg" /><div className="flex-1"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">Identidade confirmada</p><h2 className="mt-1 text-2xl font-bold tracking-tight">{provider.name}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground"><Building2 className="h-4 w-4" />{provider.company}</p></div><button type="button" onClick={() => setEditing((value) => !value)} data-testid="button-edit-provider" className="inline-flex items-center justify-center gap-2 rounded-lg border border-border px-3.5 py-2.5 text-xs font-semibold hover:border-primary/40"><Edit3 className="h-3.5 w-3.5" />{editing ? 'Cancelar edição' : 'Editar registro'}</button></div><div className="mt-8 grid gap-4 border-t border-border pt-6 sm:grid-cols-3"><div><p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Visitas registradas</p><p className="mt-1 font-mono text-2xl font-bold text-primary">{provider.visitCount}</p></div><div><p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Última entrada</p><p className="mt-2 flex items-center gap-2 text-sm font-medium"><CalendarDays className="h-4 w-4 text-accent-foreground" />{formatDate(provider.lastVisitAt)}</p></div><div><p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Cadastrado em</p><p className="mt-2 flex items-center gap-2 text-sm font-medium"><FileText className="h-4 w-4 text-muted-foreground" />{formatDate(provider.createdAt)}</p></div></div>{editing && <div className="mt-7 grid gap-4 border-t border-border pt-6 sm:grid-cols-2">{(['name','rg','company','defaultService'] as const).map((key) => <label key={key}><span className="mb-2 block text-xs font-semibold">{key === 'name' ? 'Nome' : key === 'rg' ? 'RG' : key === 'company' ? 'Empresa' : 'Serviço padrão'}</span><input value={form[key]} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} data-testid={`input-edit-${key}`} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label>)}<div className="sm:col-span-2"><button type="button" onClick={save} disabled={update.isPending} data-testid="button-save-provider" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground"><Save className="h-3.5 w-3.5" />Salvar alterações</button></div></div>}</section>
  </div>;
}