-- Execute this file once in Supabase Dashboard > SQL Editor.
-- The API uses the service_role key; browser clients use Supabase Auth only.

create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  name text not null,
  rg text not null unique,
  company text not null,
  default_service text not null,
  photo_data text,
  created_at timestamptz not null default now(),
  last_visit_at timestamptz
);

create table if not exists public.provider_visits (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  service text not null,
  entered_at timestamptz not null default now()
);

create index if not exists provider_visits_entered_at_idx
  on public.provider_visits (entered_at desc);

create index if not exists provider_visits_provider_id_idx
  on public.provider_visits (provider_id);

alter table public.providers enable row level security;
alter table public.provider_visits enable row level security;