-- Execute this file once in Supabase Dashboard > SQL Editor.
-- The API uses the service_role key; browser clients use Supabase Auth only.

create table if not exists public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  full_name text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create unique index if not exists staff_profiles_username_lower_idx
  on public.staff_profiles (lower(username));

alter table public.staff_profiles enable row level security;

-- Garante que apenas o primeiro perfil continue sendo administrador quando
-- este schema for aplicado sobre a versão anterior, que marcava todos como admin.
alter table public.staff_profiles drop constraint if exists staff_profiles_role_check;
alter table public.staff_profiles
  add constraint staff_profiles_role_check check (role in ('admin', 'user'));
alter table public.staff_profiles alter column role set default 'user';

with ranked_admins as (
  select user_id, row_number() over (order by created_at, user_id) as admin_order
  from public.staff_profiles
  where role = 'admin'
)
update public.staff_profiles as profiles
set role = case when ranked_admins.admin_order = 1 then 'admin' else 'user' end
from ranked_admins
where profiles.user_id = ranked_admins.user_id;

create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  name text not null,
  rg text not null unique,
  company text not null,
  default_service text not null,
  photo_data text,
  created_at timestamptz not null default now(),
  last_visit_at timestamptz
);

create table if not exists public.provider_visits (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  service text not null,
  entered_at timestamptz not null default now()
);

create index if not exists provider_visits_entered_at_idx
  on public.provider_visits (entered_at desc);

create index if not exists provider_visits_provider_id_idx
  on public.provider_visits (provider_id);

alter table public.providers enable row level security;
alter table public.provider_visits enable row level security;

-- O primeiro administrador é criado pelo botão "Criar administrador inicial"
-- na tela de login. Usuários seguintes são criados por um administrador.